language: c
matrix:
    include:
        - name: Linux (gcc)
          os: linux
          compiler: gcc
          addons:
            apt:
                packages:
                - libevent-dev
        - name: Linux (clang)
          os: linux
          compiler: clang
          addons:
            apt:
                packages:
                - libevent-dev
        - name: macOS
          os: osx
sudo: false
before_install:
    - [ $TRAVIS_OS_NAME = linux ] && sudo add-apt-repository -y ppa:longsleep/golang-backports
    - [ $TRAVIS_OS_NAME = linux ] && sudo apt-get update
    - [ $TRAVIS_OS_NAME = linux ] && sudo apt-get install golang-1.13-go
install:
    - [ $TRAVIS_OS_NAME = linux ] && export PATH=/usr/lib/go-1.13/bin:$PATH
    - [ $TRAVIS_OS_NAME = linux ] && export GOPATH=/usr/lib/go-1.13:$GOPATH
    - [ $TRAVIS_OS_NAME = linux ] && export GOROOT=/usr/lib/go-1.13
before_script:
    - git clone https://boringssl.googlesource.com/boringssl
    - cd boringssl
    # This is so that both GQUIC and IETF branches build.  Just picking
    # a known good revision:
    - git checkout 49de1fc2910524c888866c7e2b0db1ba8af2a530
    - cmake .
    - make
    - cd -
    - git submodule init
    - git submodule update
    - cmake -DBORINGSSL_DIR=$PWD/boringssl .
script:
    # Now build lsquic-client
    - make
    - make test
